version: "3"

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:delegated
      - deps:/home/vscode/app/deps
      - elixir_ls:/home/vscode/app/.elixir_ls
      - build:/home/vscode/app/_build
      - node_modules:/home/vscode/app/assets/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - sonic
    command: /bin/sh -c "while sleep 1000; do :; done"
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    expose:
      - "1491"
    ports:
      - "1491:1491"
    volumes:
      - ../priv/sonic/sonic.cfg:/etc/sonic.cfg
      - sonic:/var/lib/sonic/store

volumes:
  deps:
  elixir_ls:
  build:
  node_modules:
  sonic:
